PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX : <http://www.semanticweb.org/sumin/ontologies/2026/5/forestos-ontology-3#>

SELECT DISTINCT ?drug ?target ?layer (COUNT(DISTINCT ?downstream)AS ?eliminatedNodes) WHERE{
    ?drug rdf:type :Drug_Intervention .
    ?drug :perturbs_mechanistically ?target .
    
    ?target (:System_Event_Logic|:Genetic_Logic|:resolves_to)* ?downstream .
    
    ?target rdf:type ?targetClass .
    ?targetClass rdfs:subClassOf* ?layerClass .
    
    VALUES (?layerClass ?layer) {
        (:L1_Infrastructure 1)
        (:Enzyme_Level 1.5)
        (:Receptor_Level 1.5)
        (:L2_Hormone_and_biochemical_signalling 2)
        (:L3_Immune 3)
        (:L4_Genetic 4)
    }
    }

GROUPBY ?drug ?target ?layer 
ORDER BY DESC(?eliminatedNodes)}
