PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX : <http://www.semanticweb.org/sumin/ontologies/2026/5/forestos-ontology-3#>

SELECT DISTINCT ?probNode ?class ?resolvingNode ?clearState WHERE {
    :Hypercholesterolaemia_instance :has_etiology ?entry .
    ?entry (:System_Event_Logic|:Genetic_Logic|:deviates_into|:swithes_on|:switches_off)* ?probNode .
    
    FILTER EXISTS {?probNode :hasSystemState "Pathological"}
    
    ?probNode rdf:type ?class .
    FILTER(?class != owl:NamedIndividual)
    FILTER NOT EXISTS {
        ?probNode rdf:type ?subclass .
        ?subclass rdfs:subClassOf* ?class .
        Filter(?subclass != ?class)
    }
    FILTER(?class != :Disruption_Type)
    
    OPTIONAL {
        ?resolvingNode rdf:type ?class .
        ?resolvingNode :hasSystemState "Pharmacological" .
        FILTER(?resolvingNode != ?probNode)
              
    }
    BIND(IF(BOUND(?resolvingNode),"Pharmacologically Resolved","Unresolved")AS ?clearState)
        }
     

