PREFIX : <http://www.semanticweb.org/sumin/ontologies/2026/5/forestos-ontology-3#>

SELECT DISTINCT ?physioEffect ?resolveEffect ?secondaryEffect WHERE {
    ?sfa a :Saturated_Fatty_Acid .
    ?sfa :hasConcentrationState "High" .
    
    ?sfa (:System_Event_Logic|:Genetic_Logic)* ?physioEffect .
    
    OPTIONAL {
        ?physioEffect :balances_to ?resolveEffect .
        OPTIONAL {
            ?resolveEffect (:System_Event_Logic|:Genetic_Logic|:switches_on|:switches_off)+ ?mid2 .
            ?mid2 :balances_to ?secondaryEffect .
            
            FILTER(?resolveEffect != ?secondaryEffect)
        }
    }
    
    FILTER EXISTS {
        ?physioEffect :hasSystemState "Physiological"
    }
    
}
